site_name: "That's how I'm learning"
site_url: https://fluentbeat.online
site_description: It's just a random domain, you know.

repo_url: https://github.com/allanger/non-programming-languages

nav:
  - Home: index.md
  - German:
      - pages/german/index.md
      - Units: 
        - Unit 1: pages/german/units/unit_1.md
        - Unit 2: pages/german/units/unit_2.md 
  - Books:
    - The Little Prince:
      - 'German: Der Kleine Kinder': pages/books/little_prince/german.md
extra_css:
  - assets/css/custom.css
  - assets/css/hint.css
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate 



markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
extra_javascript:
  - assets/javascript/tablesort.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js

plugins:
  - search
  - section-index
  - tooltips

extra:
  search:
    lang:
      - en
  version:
    provider: mike
